---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo-app
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: todo-app-placement
        requeueAfterSeconds: 100
  template:
    metadata:
      name: todo-app-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/CSA-RH/argodemo1_todo-app-stateless-push.git
        targetRevision: main
        path: kustomize/overlays/prod
      destination:
        server: "{{server}}"
        namespace: todo-app
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true


